CS2113-AY1819S1-W13-1/main

build.gradle, docs/DeveloperGuide.adoc, docs/UserGuide.adoc, src/main/java/seedu/address/commons/core/Config.java, src/main/java/seedu/address/logic/commands/TagCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/TagCommandParser.java, src/main/java/seedu/address/model/tag/TagsContainsKeywords.java, src/test/java/seedu/address/commons/core/ConfigTest.java
Now you can use command "tag" OR "t" + "arguments" (Case-sensitive) to do a find by groups (group feature)
=> Fix some parts of the documentation and add search by Tag feature

docs/DeveloperGuide.adoc, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/person/Phone.java, src/main/java/seedu/address/model/tag/Tag.java, src/main/java/seedu/address/storage/XmlAdaptedPerson.java, src/main/java/seedu/address/storage/XmlAdaptedTag.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java, src/test/java/seedu/address/ui/PersonListPanelTest.java, src/test/java/systemtests/AddCommandSystemTest.java, src/test/java/systemtests/EditCommandSystemTest.java
Reference: https://github.com/nus-cs2103-AY1819S1/forum/issues/53
No idea whether it's even relevant to us, but bug fixes are always nice to have, right?
=> Merge from upstream se-edu/AB4

.gitignore, config.json
=> Change app name in config.json, add config.json to .gitignore

config.json
Let's hope this permanently fixes our problem
=> Removed config.json from tracked files

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/commands/LogoutCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/security/SecurityManager.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/UiManager.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/security/SecurityManagerTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java, src/test/java/systemtests/AddressBookSystemTest.java
Logout UI looks clean when logging out, systems and unit test implemented to use with SecurityManager. 
Next PR will be on the use of a database.
=> Logout UI with logout command 

src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/model/util/SampleTimeTableUtil.java, src/main/java/seedu/address/ui/TimeTablePanelMainGrid.java
=> Add sample timetables

src/main/java/seedu/address/logic/commands/SelectCommand.java, src/main/java/seedu/address/logic/parser/SelectCommandParser.java, src/main/java/seedu/address/ui/FriendListPanel.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/OtherListPanel.java, src/test/java/seedu/address/logic/commands/SelectCommandTest.java, src/test/java/seedu/address/ui/PersonListPanelTest.java
Don't you just love it when a change breaks all the system tests?
Waiting on other PR before I try to fix, maybe we should just abandon all the system tests lol
Addresses #73
=> Fix select command

src/main/java/seedu/address/logic/commands/TagCommand.java, src/test/java/seedu/address/logic/commands/TagCommandTest.java, src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
Tests are not complete, the test base is still unable to recognise a current test `User` so I have left them out for now
=> Added TagCommand tests

src/test/java/seedu/address/logic/commands/TagCommandTest.java
Fast fix for merge conflict
Remind me to re-run travis before merging anything, especially if there's a lot of merging going on.
=> Fix TagCommandTest

src/main/java/seedu/address/model/person/FriendListPredicate.java, src/main/java/seedu/address/model/person/OtherListPredicate.java, src/test/java/systemtests/AddressBookSystemTest.java
Following what Nian Fei said seems to have averted the issue for now
=> Fixed "Me" appearing in Other's panel

docs/UserGuide.adoc, src/main/java/seedu/address/logic/commands/FriendCommand.java, src/main/java/seedu/address/logic/commands/ListCommand.java, src/main/java/seedu/address/logic/commands/TagCommand.java, src/main/java/seedu/address/logic/commands/UnfriendCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/test/java/seedu/address/logic/commands/ListCommandTest.java, src/test/java/seedu/address/ui/CommandBoxTest.java
=> Fixed "List" Command. Updated aliases. Updated UG to reflect changes.

docs/UserGuide.adoc, src/main/java/seedu/address/logic/commands/FriendCommand.java, src/main/java/seedu/address/logic/commands/ListCommand.java, src/main/java/seedu/address/logic/commands/TagCommand.java, src/main/java/seedu/address/logic/commands/UnfriendCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/ui/FriendListPanel.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/OtherListPanel.java, src/main/java/seedu/address/ui/OtherPersonCard.java, src/main/resources/view/MainWindow.fxml, src/main/resources/view/OtherListPanel.fxml, src/test/java/seedu/address/logic/commands/ListCommandTest.java, src/test/java/seedu/address/ui/CommandBoxTest.java, src/test/java/seedu/address/ui/PersonListPanelTest.java
After friend-ing someone, the card will be revealed to show everything about the user.
=> Fixed GUI to only show name and index in Others panel

src/main/java/seedu/address/ui/OtherPersonCard.java
=> Fixed UI to show tags in others

src/main/java/seedu/address/logic/commands/FindCommand.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java
Now doing `Find Paul` will show the Pauls' that are found in both panels
=> Quick fix for "Find" Command

.gitignore, build.gradle, src/main/java/seedu/address/model/UserPrefs.java, src/main/resources/view/MainWindow.fxml
Continuation of #158 
Used 1280x720 because it's a common screen resolution
Closes #94
=> Changed min app size to 1280x720

src/main/java/seedu/address/model/util/SampleDataUtil.java
=> Sample data updates

src/main/java/seedu/address/ui/OtherPersonCard.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/DarkTheme.css
Done with help from AB4 Dev guide, just to improve the UI slightly
=> Added colours to group tags

src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/security/AppUsers.java
I created default accounts on top of test, the usernames are as follows:
- NF
- Ben
- Jasper
- Alexis
With 'test' as password.
You would have to delete users.json and the addressbook.xml inside data at root for the app to initiate the sample data again
=> Default accounts 

src/main/java/seedu/address/commons/CommandsEnum.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/FreeCommand.java, src/main/java/seedu/address/logic/commands/HistoryCommand.java, src/main/java/seedu/address/logic/commands/LoginCommand.java, src/main/java/seedu/address/logic/commands/LogoutCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/resources/view/MainWindow.fxml
=> Added Alias + Removed Logout Button

src/main/java/seedu/address/logic/commands/FreeCommand.java, src/main/java/seedu/address/model/util/SampleDataUtil.java
1) Remove space in sample tag
2) Print names instead of index when using free command
=> Various enhancements and bug fixes

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/ui/MainWindow.java
Logic API has changed to include updateTimeTable
=> User timetable is seen right after logging in

docs/DeveloperGuide.adoc
=> Instructions for Manual Testing in DG

src/main/java/seedu/address/logic/commands/RegisterCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/test/java/seedu/address/commons/ModelManagerTestUserStub.java, src/test/java/seedu/address/logic/commands/ModelStub.java, src/test/java/seedu/address/logic/commands/RegisterCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/RegisterCommandTest.java
=> Bug fix for allowing users with same name to register

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/commons/core/Config.java, src/test/java/seedu/address/commons/core/ConfigTest.java
I'll merge this right before I close the milestone tomorrow
=> Update version to v1.4

docs/UserGuide.adoc, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/model/person/Person.java
Help hunt for things I missed, because there's bound to be some.
Also removed the last section of the UG while I was at it
=> Changed all outward-facing mentions of tags to groups
